name: CI
on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint (ruff)
        run: ruff check .
      - name: Type check (mypy)
        run: mypy .
      - name: Tests
        run: pytest --maxfail=1 --disable-warnings --html=reports/ci_report.html || true
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/ci_report.html
      - name: Fail if tests failed
        run: |
          # make pytest failures fail the job after artifact upload
          pytest --maxfail=1 --disable-warnings -q
